// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/items.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item represents an item in the dashboard
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string                 `protobuf:"bytes,3,opt,name=shape,proto3" json:"shape,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Item) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// GroupedItems represents a collection of items grouped by a property
type GroupedItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Property      string                 `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedItems) Reset() {
	*x = GroupedItems{}
	mi := &file_proto_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedItems) ProtoMessage() {}

func (x *GroupedItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedItems.ProtoReflect.Descriptor instead.
func (*GroupedItems) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{1}
}

func (x *GroupedItems) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupedItems) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *GroupedItems) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetItemsRequest is the request for getting items
type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterBy      string                 `protobuf:"bytes,1,opt,name=filter_by,json=filterBy,proto3" json:"filter_by,omitempty"`
	FilterValue   string                 `protobuf:"bytes,2,opt,name=filter_value,json=filterValue,proto3" json:"filter_value,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_proto_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsRequest) GetFilterBy() string {
	if x != nil {
		return x.FilterBy
	}
	return ""
}

func (x *GetItemsRequest) GetFilterValue() string {
	if x != nil {
		return x.FilterValue
	}
	return ""
}

func (x *GetItemsRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

// GetItemsResponse is the response containing grouped items
type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupedItems        `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	AllColors     []string               `protobuf:"bytes,2,rep,name=all_colors,json=allColors,proto3" json:"all_colors,omitempty"`
	AllShapes     []string               `protobuf:"bytes,3,rep,name=all_shapes,json=allShapes,proto3" json:"all_shapes,omitempty"`
	AllCategories []string               `protobuf:"bytes,4,rep,name=all_categories,json=allCategories,proto3" json:"all_categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_proto_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemsResponse) GetGroups() []*GroupedItems {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetItemsResponse) GetAllColors() []string {
	if x != nil {
		return x.AllColors
	}
	return nil
}

func (x *GetItemsResponse) GetAllShapes() []string {
	if x != nil {
		return x.AllShapes
	}
	return nil
}

func (x *GetItemsResponse) GetAllCategories() []string {
	if x != nil {
		return x.AllCategories
	}
	return nil
}

// ErrorResponse is a standard error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_items_proto protoreflect.FileDescriptor

const file_proto_items_proto_rawDesc = "" +
	"\n" +
	"\x11proto/items.proto\x12\tdashboard\"^\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x14\n" +
	"\x05shape\x18\x03 \x01(\tR\x05shape\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"p\n" +
	"\fGroupedItems\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bproperty\x18\x02 \x01(\tR\bproperty\x12%\n" +
	"\x05items\x18\x03 \x03(\v2\x0f.dashboard.ItemR\x05items\"l\n" +
	"\x0fGetItemsRequest\x12\x1b\n" +
	"\tfilter_by\x18\x01 \x01(\tR\bfilterBy\x12!\n" +
	"\ffilter_value\x18\x02 \x01(\tR\vfilterValue\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\"\xa8\x01\n" +
	"\x10GetItemsResponse\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.dashboard.GroupedItemsR\x06groups\x12\x1d\n" +
	"\n" +
	"all_colors\x18\x02 \x03(\tR\tallColors\x12\x1d\n" +
	"\n" +
	"all_shapes\x18\x03 \x03(\tR\tallShapes\x12%\n" +
	"\x0eall_categories\x18\x04 \x03(\tR\rallCategories\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB#Z!github.com/elodin/dashboard/protob\x06proto3"

var (
	file_proto_items_proto_rawDescOnce sync.Once
	file_proto_items_proto_rawDescData []byte
)

func file_proto_items_proto_rawDescGZIP() []byte {
	file_proto_items_proto_rawDescOnce.Do(func() {
		file_proto_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)))
	})
	return file_proto_items_proto_rawDescData
}

var file_proto_items_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_items_proto_goTypes = []any{
	(*Item)(nil),             // 0: dashboard.Item
	(*GroupedItems)(nil),     // 1: dashboard.GroupedItems
	(*GetItemsRequest)(nil),  // 2: dashboard.GetItemsRequest
	(*GetItemsResponse)(nil), // 3: dashboard.GetItemsResponse
	(*ErrorResponse)(nil),    // 4: dashboard.ErrorResponse
}
var file_proto_items_proto_depIdxs = []int32{
	0, // 0: dashboard.GroupedItems.items:type_name -> dashboard.Item
	1, // 1: dashboard.GetItemsResponse.groups:type_name -> dashboard.GroupedItems
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_items_proto_init() }
func file_proto_items_proto_init() {
	if File_proto_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_items_proto_goTypes,
		DependencyIndexes: file_proto_items_proto_depIdxs,
		MessageInfos:      file_proto_items_proto_msgTypes,
	}.Build()
	File_proto_items_proto = out.File
	file_proto_items_proto_goTypes = nil
	file_proto_items_proto_depIdxs = nil
}
